# Generated by Django 4.0 on 2022-03-05 14:08

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('masjid_name', models.CharField(default='Open Mosque Project', max_length=255)),
                ('city', models.CharField(default='London', max_length=255)),
                ('country', models.CharField(default='GB', max_length=255)),
                ('method', models.CharField(choices=[(0, 'Shia Ithna-Ansari'), (1, 'University of Islamic Sciences, Karachi'), (2, 'Islamic Society of North America'), (3, 'Muslim World League'), (4, 'Umm Al-Qura University, Makkah'), (5, 'Egyptian General Authority of Survey'), (7, 'Institute of Geophysics, University of Tehran'), (8, 'Gulf Region'), (9, 'Kuwait'), (10, 'Qatar'), (11, 'Majlis Ugama Islam Singapura, Singapore'), (12, 'Union Organization islamic de France'), (13, 'Diyanet İşleri Başkanlığı, Türkiye')], default=3, max_length=2)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
