# Generated by Django 4.0 on 2022-03-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreprofile',
            name='asr_jamaah_minutes',
            field=models.CharField(choices=[('5', 'Jamaah is 5 minutes after Iqamah'), ('10', 'Jamaah is 10 minutes after Iqamah'), ('15', 'Jamaah is 15 minutes after Iqamah'), ('round_to_fifteen', 'Jamaah is rounded to closest 15 minutes after Iqamah'), ('round_to_thirty', 'Jamaah is rounded to closest 30 minutes after Iqamah')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='dhuhr_jamaah_minutes',
            field=models.CharField(choices=[('5', 'Jamaah is 5 minutes after Iqamah'), ('10', 'Jamaah is 10 minutes after Iqamah'), ('15', 'Jamaah is 15 minutes after Iqamah'), ('round_to_fifteen', 'Jamaah is rounded to closest 15 minutes after Iqamah'), ('round_to_thirty', 'Jamaah is rounded to closest 30 minutes after Iqamah')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='fajr_jamaah_minutes',
            field=models.CharField(choices=[('5', 'Jamaah is 5 minutes after Iqamah'), ('10', 'Jamaah is 10 minutes after Iqamah'), ('15', 'Jamaah is 15 minutes after Iqamah'), ('round_to_fifteen', 'Jamaah is rounded to closest 15 minutes after Iqamah'), ('round_to_thirty', 'Jamaah is rounded to closest 30 minutes after Iqamah')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='isha_jamaah_minutes',
            field=models.CharField(choices=[('5', 'Jamaah is 5 minutes after Iqamah'), ('10', 'Jamaah is 10 minutes after Iqamah'), ('15', 'Jamaah is 15 minutes after Iqamah'), ('round_to_fifteen', 'Jamaah is rounded to closest 15 minutes after Iqamah'), ('round_to_thirty', 'Jamaah is rounded to closest 30 minutes after Iqamah')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=51.443909, max_digits=9),
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.21973, max_digits=9),
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='maghrib_jamaah_minutes',
            field=models.CharField(choices=[('5', 'Jamaah is 5 minutes after Iqamah'), ('10', 'Jamaah is 10 minutes after Iqamah'), ('15', 'Jamaah is 15 minutes after Iqamah'), ('round_to_fifteen', 'Jamaah is rounded to closest 15 minutes after Iqamah'), ('round_to_thirty', 'Jamaah is rounded to closest 30 minutes after Iqamah')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='school',
            field=models.IntegerField(choices=[(0, 'Shafii (the standard method)'), (1, 'Hanafi')], default=0),
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='shafaq',
            field=models.CharField(choices=[('general', 'General'), ('ahmer', 'Ahmer'), ('abyad', 'Abyad')], default='general', max_length=10),
        ),
    ]
