# Generated by Django 4.0 on 2022-03-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_centreprofile_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentreProfile',
        ),
    ]
