# Generated by Django 5.1.6 on 2025-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('masjid_Name', models.CharField(default='Open Mosque Project', max_length=255, verbose_name='Name of mosque')),
                ('masjid_Logo', models.ImageField(default='images/gsm_logo.png', upload_to='images/')),
                ('masjid_Photo', models.ImageField(blank=True, upload_to='images/')),
                ('established', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2000)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='London', max_length=255)),
                ('country', models.CharField(default='GB', max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('method', models.IntegerField(choices=[(0, 'Shia Ithna-Ansari'), (1, 'University of Islamic Sciences, Karachi'), (2, 'Islamic Society of North America'), (3, 'Muslim World League'), (4, 'Umm Al-Qura University, Makkah'), (5, 'Egyptian General Authority of Survey'), (7, 'Institute of Geophysics, University of Tehran'), (8, 'Gulf Region'), (9, 'Kuwait'), (10, 'Qatar'), (11, 'Majlis Ugama Islam Singapura, Singapore'), (12, 'Union Organization islamic de France'), (13, 'Diyanet İşleri Başkanlığı, Türkiye')], default=3)),
                ('shafaq', models.CharField(choices=[('general', 'General'), ('ahmer', 'Ahmer'), ('abyad', 'Abyad')], default='general', max_length=10)),
                ('school', models.IntegerField(choices=[(0, 'Shafii (the standard method)'), (1, 'Hanafi')], default=0)),
                ('latitude', models.DecimalField(decimal_places=6, default=51.443909, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.21973, max_digits=9)),
                ('fajr_jamaah_minutes', models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255)),
                ('dhuhr_jamaah_minutes', models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255)),
                ('asr_jamaah_minutes', models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255)),
                ('maghrib_jamaah_minutes', models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255)),
                ('isha_jamaah_minutes', models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255)),
                ('theme_choice', models.CharField(choices=[('light', 'light'), ('dark', 'dark'), ('cupcake', 'cupcake'), ('bumblebee', 'bumblebee'), ('emerald', 'emerald'), ('corporate', 'corporate'), ('synthwave', 'synthwave'), ('retro', 'retro'), ('cyberpunk', 'cyberpunk'), ('valentine', 'valentine'), ('halloween', 'halloween'), ('garden', 'garden'), ('forest', 'forest'), ('aqua', 'aqua'), ('lofi', 'lofi'), ('pastel', 'pastel'), ('fantasy', 'fantasy'), ('wireframe', 'wireframe'), ('black', 'black'), ('luxury', 'luxury'), ('dracula', 'dracula'), ('cmyk', 'cmyk'), ('autumn', 'autumn'), ('business', 'business'), ('acid', 'acid'), ('lemonade', 'lemonade'), ('night', 'night'), ('coffee', 'coffee'), ('winter', 'winter')], default='light', max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('youtube', models.CharField(blank=True, max_length=255)),
                ('telegram', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('tiktok', models.CharField(blank=True, max_length=255)),
                ('imam', models.CharField(blank=True, max_length=255)),
                ('landline', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('what3words', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('light', 'light'), ('dark', 'dark'), ('cupcake', 'cupcake'), ('bumblebee', 'bumblebee'), ('emerald', 'emerald'), ('corporate', 'corporate'), ('synthwave', 'synthwave'), ('retro', 'retro'), ('cyberpunk', 'cyberpunk'), ('valentine', 'valentine'), ('halloween', 'halloween'), ('garden', 'garden'), ('forest', 'forest'), ('aqua', 'aqua'), ('lofi', 'lofi'), ('pastel', 'pastel'), ('fantasy', 'fantasy'), ('wireframe', 'wireframe'), ('black', 'black'), ('luxury', 'luxury'), ('dracula', 'dracula'), ('cmyk', 'cmyk'), ('autumn', 'autumn'), ('business', 'business'), ('acid', 'acid'), ('lemonade', 'lemonade'), ('night', 'night'), ('coffee', 'coffee'), ('winter', 'winter')], default='light', max_length=100)),
            ],
        ),
    ]
