# Generated by Django 6.0 on 2026-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreprofile',
            name='weekly_schedule',
            field=models.JSONField(default={'friday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}, 'monday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}, 'saturday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}, 'sunday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}, 'thursday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}, 'tuesday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}, 'wednesday': {'asr_jamaah': True, 'dhuhr_jamaah': True, 'fajr_jamaah': True, 'isha_jamaah': True, 'maghrib_jamaah': True, 'open': True}}, help_text='Schedule of operating days and prayers with jamaah times'),
        ),
    ]
