# Generated by Django 4.0 on 2022-11-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centreprofile',
            old_name='masjidLogo',
            new_name='masjid_Logo',
        ),
        migrations.RenameField(
            model_name='centreprofile',
            old_name='masjid_name',
            new_name='masjid_Name',
        ),
        migrations.RenameField(
            model_name='centreprofile',
            old_name='masjidPhoto',
            new_name='masjid_Photo',
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='asr_jamaah_minutes',
            field=models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='dhuhr_jamaah_minutes',
            field=models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='fajr_jamaah_minutes',
            field=models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='isha_jamaah_minutes',
            field=models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='maghrib_jamaah_minutes',
            field=models.CharField(blank=True, choices=[('5', 'Jamaat (Iqamah) is 5 minutes after Azan'), ('10', 'Jamaat (Iqamah) is 10 minutes after Azan'), ('15', 'Jamaat (Iqamah) is 15 minutes after Azan'), ('round_to_fifteen', 'Jamaat (Iqamah) is rounded to closest 15 minutes after Azan'), ('round_to_thirty', 'Jamaat (Iqamah) is rounded to closest 30 minutes after Azan')], max_length=255),
        ),
    ]
