# Generated by Django 4.0 on 2022-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreprofile',
            name='about',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='method',
            field=models.IntegerField(choices=[(0, 'Shia Ithna-Ansari'), (1, 'University of Islamic Sciences, Karachi'), (2, 'Islamic Society of North America'), (3, 'Muslim World League'), (4, 'Umm Al-Qura University, Makkah'), (5, 'Egyptian General Authority of Survey'), (7, 'Institute of Geophysics, University of Tehran'), (8, 'Gulf Region'), (9, 'Kuwait'), (10, 'Qatar'), (11, 'Majlis Ugama Islam Singapura, Singapore'), (12, 'Union Organization islamic de France'), (13, 'Diyanet İşleri Başkanlığı, Türkiye')], default=3),
        ),
    ]
