# Generated by Django 5.1.6 on 2025-02-21 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreprofile',
            name='theme_choice',
            field=models.ForeignKey(choices=[('light', 'light'), ('dark', 'dark'), ('cupcake', 'cupcake'), ('bumblebee', 'bumblebee'), ('emerald', 'emerald'), ('corporate', 'corporate'), ('synthwave', 'synthwave'), ('retro', 'retro'), ('cyberpunk', 'cyberpunk'), ('valentine', 'valentine'), ('halloween', 'halloween'), ('garden', 'garden'), ('forest', 'forest'), ('aqua', 'aqua'), ('lofi', 'lofi'), ('pastel', 'pastel'), ('fantasy', 'fantasy'), ('wireframe', 'wireframe'), ('black', 'black'), ('luxury', 'luxury'), ('dracula', 'dracula'), ('cmyk', 'cmyk'), ('autumn', 'autumn'), ('business', 'business'), ('acid', 'acid'), ('lemonade', 'lemonade'), ('night', 'night'), ('coffee', 'coffee'), ('winter', 'winter')], default='light', on_delete=django.db.models.deletion.CASCADE, to='masjidConfig.theme'),
        ),
    ]
