# Generated by Django 4.0 on 2022-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
