# Generated by Django 4.0 on 2022-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0002_rename_masjidlogo_centreprofile_masjid_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centreprofile',
            name='accentColour',
        ),
        migrations.RemoveField(
            model_name='centreprofile',
            name='mainColour',
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='theme_choice',
            field=models.CharField(blank=True, choices=[(0, 'default theme'), (1, 'Dark Theme')], max_length=255),
        ),
        migrations.AlterField(
            model_name='centreprofile',
            name='masjid_Name',
            field=models.CharField(default='Open Mosque Project', max_length=255, verbose_name='Name of mosque'),
        ),
    ]
