# Generated by Django 6.0 on 2026-01-03 16:43

import masjidConfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0002_centreprofile_weekly_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreprofile',
            name='weekly_schedule',
            field=models.JSONField(default=masjidConfig.models.get_default_schedule, help_text='Schedule of operating days and prayers with jamaah times'),
        ),
    ]
