# Generated by Django 4.0 on 2022-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0002_centreprofile_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centreprofile',
            old_name='contactName',
            new_name='imam',
        ),
        migrations.AddField(
            model_name='centreprofile',
            name='masjidPhoto',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
