# Generated by Django 5.1.6 on 2025-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjidConfig', '0003_alter_centreprofile_theme_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreprofile',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
